apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argo-cd
spec:
  destination:
    namespace: guestbook
    server: "https://dev-ovng-poc2-lead.ovng.dev.myovcloud.com:6443"
  project: default
  source:
    path: guestbook
    repoURL: "https://github.com/mabusaa/argocd-example-apps.git"
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
