apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev-project
spec:
  description: Dev Project
  sourceRepos:
  - '*'

  # Only permit application to deploy on this repo
  destinations:
  - namespace: ns-1
    server: https://kubernetes.default.svc

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
