apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: auto-pruning-demo
spec: 
  destination:
    namespace: bnnguyen
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: guestbook-with-sub-directories
    repoURL: "https://github.com/nguyenbuitk/argocd-example-apps.git"
    targetRevision: master
    directory:
      recurse: true
  syncPolicy:
    automated: 
      # Default – no prune: when automated sync is enabled, by  default for safety automated sync will not delete resources when Argo CD detects the resource is no longer defined in 
      # this feature is used to enable it
      prune: true
      # By default, changes that are made to the live cluster will not trigger automated sync.
      # This feature is used to enable it
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
