apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: selective-sync
spec:
  destination:
    namespace: bnnguyen
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: sync-options/selective-sync
    repoURL: "https://github.com/nguyenbuitk/argocd-example-apps.git"
    targetRevision: master
    directory:
      recurse: true
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
